### GET ALL POSTS
GET http://localhost:8080/posts HTTP/1.1

### GET ONE POST
GET http://localhost:8080/posts/ac75abb1-e836-4ddf-9ee7-1493712e7413 HTTP/1.1

### POST ONE POST
POST http://localhost:8080/posts
Content-Type: application/json

{
    "title": "Changement Micro",
    "content": "Quelle association  ?"
}

### PUT POST
PUT http://localhost:8080/posts/ef8088c8-563e-4722-a8f4-71568f76cba5 HTTP/1.1
Content-Type: application/json

{    
    "title": "Réglage guitare",
    "content": "Ou ?"
}

### DELETE ONE POST
DELETE http://localhost:8080/posts/ac75abb1-e836-4ddf-9ee7-1493712e7413