### GET ALL USER
GET http://localhost:8080/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkM0B0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU5NTg2MzgwNSwiZXhwIjoxNTk1OTUwMjA1fQ.hnoNznCrd9sl3V6RdyH9iecjw98A3SssQb6T2V-XeMU

### GET ONE USER
GET  http://localhost:8080/users/f9b0485c-f517-4b4b-befd-ee924412eca4 HTTP/1.1

### POST ONE USER
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "lastName": "Loud2",
    "firstName": "Maxi",
    "email": "maxiloud3@test.com",
    "phone": "0656899858",
    "password": "totoTOTO",
    "localisation": "Baiona",
    "role" : "ADMIN",
    "logo": "ok"
}

### PUT ONE USER 
PUT http://localhost:8080/users/3ed392b6-d752-4753-b5ab-79488a31ea4b HTTP/1.1
Content-Type: application/json

{
    "lastName": "Kale",
    "firstName": "Borroka",
    "email": "maxiloud@test.com",
    "phone": "0708090605",
    "password": "totoTOTO",
    "localisation": "Baiona",
    "role": "ADMIN",
    "logo": "ok"
}

### DELETE ONE USER
DELETE http://localhost:8080/users/42421d6c-c236-4663-af9f-b1d1ed8f9595 HTTP/1.1