### GET ALL USER
GET http://localhost:8080/users HTTP/1.1

### GET ONE USER
GET  http://localhost:8080/users/f9b0485c-f517-4b4b-befd-ee924412eca4 HTTP/1.1

### POST ONE USER
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "lastName": "Loud2",
    "firstName": "Maxi",
    "email": "maxiloud2@test.com",
    "phone": "0656899858",
    "password": "totoTOTO",
    "localisation": "Baiona",
    "logo": "ok"
}

### PUT ONE USER 
PUT http://localhost:8080/users/5527e08a-9d5c-4d0e-b50e-2362a908d7e0 HTTP/1.1
Content-Type: application/json

{
    "lastName": "Kale",
    "firstName": "Borroka",
    "email": "maxiloud@test.com",
    "phone": "0708090605",
    "password": "totoTOTO",
    "localisation": "Baiona",
    "logo": "ok"
}

### DELETE ONE USER
DELETE http://localhost:8080/users/f9b0485c-f517-4b4b-befd-ee924412eca4 HTTP/1.1