### GET ALL USERTYPES
GET http://localhost:8080/usertypes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTk2MDQ1ODk4LCJleHAiOjE1OTYxMzIyOTh9.Rd9b-s45hDBXE_RPsepnfnEYivOHIt2FrUlP0poIX8w

### GET ONE USERTYPE
GET  http://localhost:8080/usertypes/3cfe76c0-18f6-40fa-a0f7-ce7935f5c789 HTTP/1.1
Authorization: Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTk2MDQ1ODk4LCJleHAiOjE1OTYxMzIyOTh9.Rd9b-s45hDBXE_RPsepnfnEYivOHIt2FrUlP0poIX8w

### POST ONE USERTYPE
POST http://localhost:8080/usertypes HTTP/1.1
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTk2MDQ1ODk4LCJleHAiOjE1OTYxMzIyOTh9.Rd9b-s45hDBXE_RPsepnfnEYivOHIt2FrUlP0poIX8w
Content-Type: application/json

{
    "label": "Professionnel"
}

### PUT ONE USER 
PUT http://localhost:8080/usertypes/cfe76c0-18f6-40fa-a0f7-ce7935f5c789 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTk2MDQ1ODk4LCJleHAiOjE1OTYxMzIyOTh9.Rd9b-s45hDBXE_RPsepnfnEYivOHIt2FrUlP0poIX8w
Content-Type: application/json

{
    "label": "Professionnel(le)"
    
}

### DELETE ONE USERTYPE
DELETE http://localhost:8080/usertypes/5961010f-33b1-40da-8782-e864391f5c31 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1heGlsb3VkQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTk2MDQ1ODk4LCJleHAiOjE1OTYxMzIyOTh9.Rd9b-s45hDBXE_RPsepnfnEYivOHIt2FrUlP0poIX8w